### ISSUE TITLE
Explanation on multiple target reflection

### ISSUE THREAD

**Issue by matejthetree** [dart-lang/reflectable#123]
Hello,

I have few questions.

1. Is it possible to reflect all classes that have implementations of an certain interface in a program?
2. Is it possible to reflect all classes that use certain metadata (on setters, constructor or fields) in a program?
3. Is it possible to reflect all classes inside one `.dart.` file?
4. example: `class A extends B{}`, `class C extends B{}`, ...
 where `abstract class B{}` Is it possible to reflect all classes that extend `B`?

p.s. I believe that some of this cases are explained in `capabilitiy.dart`. The explanations are a little confusing for me so If someone has quick response with examples, that would help a lot. 
If not, I will update my question as I stumble upon answers tomorrow.

**Comment by matejthetree** [comment]
2. I am trying to use `GlobalQuantifyMetaCapability`

Here is how I try to set it up

```
@InjectMetaCapability()
import 'package:reflectable/reflectable.dart';
...
const Reflect reflect = const Reflect();

class InjectMetaCapability extends GlobalQuantifyMetaCapability{
  const InjectMetaCapability() : super(Inject, reflect);
}
```
```
class Reflect extends Reflectable {
  const Reflect()
      : super(
            invokingCapability,
            typingCapability,
            const SuperclassQuantifyCapability(Object,
                excludeUpperBound: false));
}
```
later If I just mark my property with `@Inject`, the class doesn't get reflected once I run build script.

**Comment by matejthetree** [comment]
I am trying to use GlobalQuantifyCapability with same problems. I must be setting it up wrong.

```
@CatNameCapability()
import 'package:reflectable/reflectable.dart';
```
```
class CatNameCapability extends GlobalQuantifyCapability{
  const CatNameCapability() : super("Cat", reflect);
}
```
```
class CatClass{}

class CatClassWithValueHolder{
  @inject
  ValueHolder valueHolder;
}
```
None of the`Cat*` classes get reflected

**Comment by eernstg** [comment]
Sorry about the delay, catching up after the holidays. ;)

> reflect all classes that have implementations of an certain interface

Check out [`subtypeQuantifyCapability`](https://github.com/dart-lang/reflectable/blob/eb7d34f11cf0c972aaf379f111dcc9cd4f206ce9/lib/capability.dart#L329).

> reflect all classes that use certain metadata

Do you mean like `@certainMetadata class C {...}`? For that, check out [`GlobalQuantifyMetaCapability`](https://github.com/dart-lang/reflectable/blob/eb7d34f11cf0c972aaf379f111dcc9cd4f206ce9/lib/capability.dart#L445), e.g., [here](https://github.com/dart-lang/test_reflectable/blob/ce90403b3f70d397ebde3fc1a48e46ac224a00cd/test/global_quantify_test.dart#L37).

> all classes inside one .dart. file.

There is no special support for such a thing, but you might be able to use a global quantifier and maybe some name based matching. [Here](https://github.com/dart-lang/test_reflectable/blob/ce90403b3f70d397ebde3fc1a48e46ac224a00cd/test/global_quantify_test.dart#L7)'s an example which relies on the full name (which relies on the `library`, which you may wish to add if there isn't any, for that purpose).

> reflect all classes that extend `B`

There is no support for that specific quantification. You can reflect on classes that extend or implement `B` (that is, its subtypes), or all superclasses of `B`, but not all subclasses (without other subtypes). Are you sure you want the subclasses without other subtypes? Note that whenever you know that a given instance has type `T` statically you can rely on it being an instance of a subtype, but it doesn't have to be an instance of a subclass (so you can't rely on being able to do `myReflector.reflect(thatInstance)` based on the static type), so you'd typically need subtype quantification. Otherwise you'd need to express the desired set of classes in some other way.

**Comment by matejthetree** [comment]
@eernstg thank you :) I hope you enjoyed your holidays.

> Do you mean like @certainMetadata class C {...}? For that, check out GlobalQuantifyMetaCapability, e.g., here.

I was thinking, If I put my custom metadata like `@inject` on a property, setter or a method, can reflectable recognize that based on one of capabilities, and reflect that class?

The link for name based matching is not working. I was looking forward to see how that works :) Since in my test, I couldnt get name based matching to work.

**Comment by eernstg** [comment]
> later If I just mark my property with @Inject, the class doesn't get reflected once I run build script.

You need to use the `GlobalQuantifyMetaCapability` as metadata on an import of `reflectable.dart` in order to create the association between the metadata and the given reflector. [Here](https://github.com/dart-lang/test_reflectable/blob/ce90403b3f70d397ebde3fc1a48e46ac224a00cd/test/global_quantify_test.dart#L7) is an example. In that example we request that every class whose full name matches `r"^test_reflectable.test.global_quantify_test.(A|B)$"` be covered by the reflector `reflector`, which works just like putting `@reflector` on every one of those classes.

In general, you should not create a subtype of any capability class, ever.

**Comment by matejthetree** [comment]
I get 404 even on that [last link](https://github.com/dart-lang/test_reflectable/blob/master/test/global_quantify_test.dart) you provided.

**Comment by matejthetree** [comment]
Thank you, I will look into your examples.

**Comment by eernstg** [comment]
Links should be OK now!

**Comment by eernstg** [comment]
Issues raised here should be clarified by now, closing.
