### ISSUE TITLE
reflecting on a Class with default optional constructor parameters

### ISSUE THREAD

**Issue by matejthetree** [dart-lang/reflectable#124]
Hello,

```
@Reflect()
class ValueHolder {
  final String value;

  const ValueHolder([this.value = "defaultValue"]);
}

```
This is the class, and this is parameters that I get on it.

<img width="326" alt="screen shot 2018-03-29 at 14 51 43" src="https://user-images.githubusercontent.com/10059426/38110464-5dd6e44a-3361-11e8-891a-6f252fd657fc.png">

Is this expected behaviour, and if yes is there a capability to map all arguments as well? Something like mapping all superclasses?

Thank you

**Comment by eernstg** [comment]
It is an implementation detail whether `_defaultValue` is null, that is just a cache for the default value. So you'd need to call `myParameterMirror.defaultValue` in order to see that you get the right default value. It should work, cf. [the parameter `z`](https://github.com/dart-lang/test_reflectable/blob/ce90403b3f70d397ebde3fc1a48e46ac224a00cd/test/parameter_test.dart#L65)which seems to be similar to your example.

**Comment by eernstg** [comment]
Closing, I believe the issues raised here have been clarified.
