### ISSUE TITLE
build_runner support for specific tests

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/reflectable#133]
Say I have some tests in `test/unit/directive`. dart_test.yaml sets all test by default to 'chrome'

If I run `dart tool/builder.dart test/unit/directive/*.dart && pub run test test/unit/directive/`
it generates *.reflectable.dart in this directory and everything is fine (Test takes forever because browser-tests are soooo slow - but it works)

However - if I run `pub run build_runner test -- test/unit/directive/` it generates *.reflectable.dart files for the whole project (for all tests under /test) which slows down my specific tests

Stats:
I measured each version 2 times. I slightly change one test after the first run
with tool/builder
1st run: 26.2 secs, 2nd run: 26.5 secs
with build_runner
1st run: 31.3 secs, 2nd run: 32.5 secs

**Comment by eernstg** [comment]
It looks like everything is regenerated, but you should be able to regenerate only the files that depend on something that you have actually changed. Or are you actually changing something that's imported (directly or indirectly) by every test?

Otherwise, I'd expect to be able to use `pub run build_runner build test/unit/directive` in order to generate the code incrementally.

**Comment by eernstg** [comment]
Thanks, Jacob!

**Comment by eernstg** [comment]
Closing: This issue seems to have been resolved [here](https://github.com/dart-lang/reflectable/issues/133#issuecomment-396947186).
