### ISSUE TITLE
Invoking factory

### ISSUE THREAD

**Issue by manuscle** [dart-lang/reflectable#161]
Is it possible to invoke factory?

```dart
class User {
    factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}

Class MyService {
  Future<T> getModel() {
    ClassMirror cm = reflector.reflectType(T);
    return cm.invoke('fromJson', [{'id': '5', 'name': 'foobar'}]);
  }
}
```
This code get an error:
NoSuchCapabilityError: no capability to invoke the method 'fromJson'

**Comment by eernstg** [comment]
Should be available using `newInstance`, cf. https://github.com/dart-lang/test_reflectable/blob/master/test/new_instance_test.dart.

**Comment by manuscle** [comment]
Awesome! Thanks for quick answer :-)

**Comment by charcoast** [comment]
I couldn't get this to work. I did as in the example, added newInstanceCapability and called the fromJson constructor, but I received NoSuchMethodError.

```dart
void main(){
  initializeReflectable();
  Type type = Client;
  ClassMirror typeMirror = reflector.reflectType(type) as ClassMirror;
  Map<Symbol, dynamic> namedParams = Client(clientId: 1, name: 'Birubiru', cpf: '454545454545', creationTime: DateTime.now(), lastUpdate: DateTime.now(), accountId: 10, )
      .toJson().map((key, value) => MapEntry(Symbol(key), value));
  Object? client = typeMirror.newInstance('fromJson',[],
      namedParams
  );

  print(client);
}
```



```dart
import 'package:reflectable/reflectable.dart';

class Reflector extends Reflectable {
const Reflector()
    : super(newInstanceCapability); // Request the capability to invoke methods.
}

const reflector = Reflector();
```
![image](https://github.com/google/reflectable.dart/assets/11007668/a37b26e8-ee61-4e0b-aa6e-98e8f639d79c)

**Comment by e-belair** [comment]
In my (old) project I've set the lib like this:
```
import 'package:reflectable/reflectable.dart';

class Reflector extends Reflectable {
  const Reflector()
      : super(
            invokingCapability,
            metadataCapability,
            declarationsCapability,
            typeCapability,
            typeRelationsCapability,
            reflectedTypeCapability,
            superclassQuantifyCapability);
}

const reflector = Reflector();
```
Seems to have done the job with one of these capabilities.

**Comment by eernstg** [comment]
Right, `newInstanceCapability` will enable reflective execution of constructors, not anything else (so it won't allow invocation of methods, getters, setters, whether they are global, static or instance). So you might very well need to have more capabilities.

However, for the invocation of `newInstance` I think the error arises because there is no support for the given class. We can't see the declaration of the class `Client` anywhere, and it is possible that it isn't covered by `reflector` (that means, `reflector` doesn't know anything about `Client` so it won't do anything with it).

You can cover a given declaration by a given reflector by adding that reflector as metadata to the declaration:

```dart
@reflector
class Client ...
```

You can also create the association "at a distance". See [this example](https://github.com/google/reflectable.dart/blob/master/test_reflectable/test/global_quantify_test.dart).

Finally, it might also fit your purpose to create the connection via the subtype relationship. See [this example](https://github.com/google/reflectable.dart/blob/master/test_reflectable/test/subtype_quantify_test.dart). In this case you are specifying that `reflector` must cover a given class `SupertypeOfClient`, passing a specific option to say that you want to include all subtypes, and then `Client` will be covered because it is a subtype of `SupertypeOfClient`.

**Comment by ced1check** [comment]
Hello all, I'm having a similar issue, but adding any capability doesn't make any difference.

I'm pretty sure I'm doing something wrong but after hours trying and searching I failed to make it work. Any input would be great.

Here's the class I'm trying to instanciate, it's fields and default constructor:

```
@invokeReflector
class Group extends DBNameObject {
  String? color;
  bool messaging;
  List<int> actions;
  int incidentsObjectsDisplay;
  int controlsObjectsDisplay;

  List<User> users = [];

  @constructor
  Group({
    required super.id,
    required super.libelle,
    required this.color,
    required this.messaging,
    this.actions = const [],
    this.incidentsObjectsDisplay = 1,
    this.controlsObjectsDisplay = 1,
    super.deleted,
    super.lastUpdate,
  });

```
The parent is setup in a similar way:
```
@invokeReflector
class DBNameObject extends DBObject {
  String libelle;
  DateTime lastUpdate;

  @constructor
  DBNameObject({lastUpdate, this.libelle = "", super.id, super.deleted}) : lastUpdate = lastUpdate ?? DateTime.now();

```
The reflector setup is as follows:
```
class InvokeReflector extends Reflectable {
  const InvokeReflector() : super(
      invokingCapability,
      newInstanceCapability,
      declarationsCapability,
      reflectedTypeCapability,
      typeRelationsCapability,
      metadataCapability);
}

```

Now that's the code used to get a new instance:
`classMirror.newInstance(defaultConstructor.constructorName, arguments, named);`

Howerver the output is always the same:
```
NoSuchCapabilityError: no capability to invoke the constructor ""
Receiver: Group
Arguments: []
Named arguments: {Symbol("id"): 868, Symbol("libelle"): Administrateur, Symbol("color"): null, Symbol("messaging"): 0, Symbol("actions"): [], Symbol("incidents_objects_display"): 1, Symbol("controls_objects_display"): 1, Symbol("deleted"): true, Symbol("last_update"): 2024-10-18 14:16:44.415834}

```

All required parameters are there and all optionals too, but it fails!?

I tried adding most of the capabilities I could find, tried moving a named parameter to positionnal.

All to no avail.
