### ISSUE TITLE
Calling `initializeReflectable` multiple times resets the mirror data of previous reflectors

### ISSUE THREAD

**Issue by fertrig** [dart-lang/reflectable#168]
Given reflectables `a` and `b`.
When you call `initializeReflectable` on both:
```
a.initializeReflectable();
b.initializeReflectable();
```
Then the reflector will only have the mirror data for `b`, it will not have the mirror data for `a`.

Looking at the code of `initializeReflectable`, it seems to be overriding the mirror data every time it is called.

Is this the expected behavior? If not, how can we work with multiple reflectables?

If you need code to reproduce, I found this sample code that demonstrates the issue:
https://github.com/fidlip/reftest/blob/master/bin/main.dart

**Comment by eernstg** [comment]
I need to establish the notion of an 'entry point' first. That's the "main" library of the application, which contains a top-level function called `main` (or, once in a blue moon, at least imports such a function). That library is the argument to `dart` if you execute it from the command line, and the transitive closure of its imports is exactly the libraries that your application includes at run time. So your entry point represents "the program".

Reflectable is capable of doing certain global things. For instance, it can quantify over all subtypes of a given type (and provide the features of a certain reflector for those subtypes). It is not possible to find all these subtypes unless a global analysis is performed, and this implies that reflectable's build step must have the entire program (that is, the entry point) as its build target.

Hence, your application should just contain just one '*.reflectable.dart' library, and that library is typically imported by your entry point. You would then run `initializeReflectable()` exactly once, at the beginning of `main`, and this will provide the support for all your reflectors.

Of course, each reflector may provide support for reflection on any number of classes, so you only need one reflector unless it is important for you to have different levels of reflection support for different classes. (For instance, if you only need the ability to call static methods on one set M1 of classes, and you only need to inspect the subtype graph for another set M2 of classes, and it would be too expensive in terms of code size to be able to do both for the union of M1 and M2).

I can see that you actually only have one reflector, and `a.initializeReflectable()` will set up reflectable to associate `Reflector` with the data for `A`, and then `b.initializeReflectable()` will overwrite that setup such that `Reflector` has the data for `B`, so that's the reason why you only have support for `B` after that point. So you just need to use `main.dart` rather than `class_a.dart` or `class_b.dart` as your build target for the reflectable builder, and import `main.reflectable.dart` and run `initializeReflectable()` on that&mdash;then I think it will just work.

**Comment by fertrig** [comment]
Your advice worked. Thank you!

Here's the code that shows how it works:
https://github.com/fertrig/reflectable_multiple_test

One caveat is that it seems that the `reflector` variable and `Reflector` class need to be declared in the entry point file. When I declared them in a separate file, it generated the code successfully, but I was getting runtime errors when accessing `reflector.annotatedClasses`.

I also tested it with multiple reflectors, each with different capabilities. That worked as expected.

Thanks again!

**Comment by eernstg** [comment]
@fertrig wrote:
> reflector variable and Reflector class need to be declared in the entry point file. 

That should not be necessary. Counter-example: https://github.com/dart-lang/test_reflectable/blob/master/test/meta_reflectors_test.dart.
