### ISSUE TITLE
Create generic list with type argument having only ClassMirror of this type

### ISSUE THREAD

**Issue by 4lfant** [dart-lang/reflectable#183]
Hi!
Thanks for your awesome library. It helps a lot in implementing my project.
Meanwhile I'm faced with a problem:
I cannot create generic list with type argument when I have only ClassMirror of this type.

I receive the list of objects (that can be of any type, for example Foo) from the server in json format.
```json
[
  {
    "class": "Foo",
    "variable": "value1"
  }, 
  {
    "class": "Foo",
    "variable": "value2"
  }
]
```

```dart
@reflector
class Foo {
  var variable;
}
```

On the Flutter side I want to create the list with type argument that is specified in json. For this example, it must be `List<Foo>`
I get the ClassMirror for a class `Foo` from the `annotatedClasses` of the Reflector, create the instance, assign values to the variables and add object to the list.

Reflector:
```dart
List<Map> originalList;
List objectList;

originalList.forEach((map) {
  ClassMirror classMirror = annotatedClasses.firstWhere((annotatedClass) => 
    annotatedClass.simpleName == map["class"]); // get the ClassMirror for type `Foo`

  var object = classMirror.newInstance("", []); /* create the object of type `Object`
but "under the hood" it knows it's instance of `Foo` */
  ...
  list.add(object)
});

return objectList
```
As a result, I get the `List<dynamic>`. But I expect the `List<Foo>` in another part of the application.

Having generic list with right type argument is _critical_ for my project.
I spent a lot of time on this problem. I cannot find a way to specify the generic type for the list, having only the ClassMirror of this type.

Is it even possible? And what is a way to solve this issue?

I will be very grateful for any help!

**Comment by eernstg** [comment]
There is no direct solution, because Dart does not support obtaining a type (which could be used as a type argument in the creation of a new object) from a value (say, an instance of `Type`). So if you want to create an instance of `List<Foo>` then you have to have an expression of the form `<T>[...]` (or a similar expression using a list constructor) where `T` is ultimately provided as the type `Foo`.

So you could of course create a map like `{ "Foo": () => <Foo>[], ...}` with all the types that you wish to cover, but that's surely going to be inconvenient because you (probably) don't want to create and maintain a list of all those types anywhere.

So you can't really stay completely generic (typeless) and get support for creating all those specific lists. However, you might be able to push it unto the clients without too much trouble for them.

But first, how do you know that the original list doesn't contain maps representing instances of many different types?:

``
[
  {
    "class": "Foo",
    "variable": "value1"
  }, 
  {
    "class": "Bar",
    "aBarInstanceVariable": "value2"
  }
]
```

In that case you'd need to create a list of some common supertype of all the element types, which could be anything up to `Object`. In that case you'd need to compute such a common supertype and that wouldn't be easy.

However, if you know that the original list contains instances of the same type then you might be willing to ask the authors of classes like `Foo` to mix in `ListGetter<Foo>`:

```dart
mixin ListGetter<X> {
  List<X> get listOfThis => [];
}

@reflector
class Foo with ListGetter<Foo> {}

main() {
  ListGetter<dynamic> x = Foo();
  var xs = x.listOfThis;
  print(xs.runtimeType); // `List<Foo>`, even though the type of `x` doesn't involve `Foo`.
}
```

If the list is empty you could use `const <Null>[]` (or `const <Never>[]` when we add non-nullable types), which will be able to play the role as "any empty list".

**Comment by 4lfant** [comment]
Thanks a lot for your help, explanation and possible solution, @eernstg 
I will look into it and try it out.
You are awesome! :smiley:
