### ISSUE TITLE
Too many positional arguments on reflectable-2.2.1

### ISSUE THREAD

**Issue by bounty1342** [dart-lang/reflectable#194]
Hi,

I got this error message  :

```
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../flutter/.pub-cache/hosted/pub.dartlang.org/reflectable-2.2.1/lib/src/builder_implementation.dart:5207:46: Error: Too many positional arguments: 0 allowed, but 1 found.Try removing the extra positional arguments.  InterfaceType get type => InterfaceTypeImpl(this);                                             ^../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/src/dart/element/type.dart:705:3: Context: Found this candidate, but the arguments don't match.  InterfaceTypeImpl({  ^^^^^^^^^^^^^^^^^../../flutter/.pub-cache/hosted/pub.dartlang.org/reflectable-2.2.1/lib/src/builder_implementation.dart:5214:24: Error: Too many positional arguments: 0 allowed, but 1 found.Try removing the extra positional arguments.      InterfaceTypeImpl(this);                       ^../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/src/dart/element/type.dart:705:3: Context: Found this candidate, but the arguments don't match.  
InterfaceTypeImpl({  ^^^^^^^^^^^^^^^^^
pub finished with exit code 78
```

This seems to be also encounter by the static analysis :
`Fix lib/src/builder_implementation.dart. (-46.50 points)`

Regards

**Comment by eernstg** [comment]
Yes, reflectable needs to model classes in the semantic style (where the superclass of a given class `class A extends B with M {}` is the mixin application `B with M`), because that's what operations like `ClassMirror.superclass` must return. But the analyzer takes a more syntactic perspective and considers the superclass to be the class (or parameterized type, in case it's generic) denoted by the syntax in the `extends` clause.

So we could create a completely separate set of classes wrapping the analyzer classes modeling such things as classes, or we could create this single "bridging" class that models a mixin application. Both choices are inconvenient to maintain, because we need to depend on the analyzer API beyond what was expected.

In this case it breaks because the constructor of `InterfaceTypeImpl` was changed (in dart-lang/sdk@9e7c401d4fe72898f2c5c626c19d6b6858f2bbe3), and `MixinApplication` needs to create an `InterfaceTypeImpl` in a couple of situations.

Hopefully we can find a way to provide the newly added parameters, and then it should work again. I'll take a look at this next week.

**Comment by eernstg** [comment]
Reflectable 2.1.1+1 has been published; it requires the analyzer to have version 0.39.0-0.39.3 and hence avoids the breakage reported here. A solution that works with 0.39.4 is upcoming.

**Comment by eernstg** [comment]
Reflectable 2.1.1+2 has been published; it requires the analyzer to have version 0.39.4 and resolves the problem with the obsolete usage of the `InterfaceTypeImpl` constructor.

We're pinning the version of reflectable to the version of analyzer, so for every new version of the analyzer we must publish a new version of reflectable to go with it (or widen the version range for analyzer, if the new analyzer doesn't break the current reflectable). That would prevent breakage of the kind that we've seen in this issue.
