### ISSUE TITLE
Use reflectable in multiple pages 

### ISSUE THREAD

**Issue by bonfry** [dart-lang/reflectable#200]
Hi, I want to know if I can use the reflectable library in multiple files. For instance: 

main.dart for initializing

```dart
void main() {
  initializeReflectable();
  return runApp(MyApp());
}
```

money_budget.dart for reflecting a model

```dart

class Table {
  const Table(this.tableName);
  final String tableName;
}

@AppReflectable()
@dbHelper.Table('money_budget')
class MoneyBudget implements IModel {
  int id;
  String title;
  Color color;

  MoneyBudget({
    this.id,
    this.title,
    this.color,
  });

  @override
  Map<String, dynamic> toMap() {
    return {"id": id, "title": title, "color": color.value};
  }

  static MoneyBudget parseMap(Map<String, dynamic> map) {
    return MoneyBudget(
        id: map["id"], title: map["title"], color: Color(map["color"].round()));
  }
}
```

And a generic class for managing models, which has been written in another file

```dart
class DatabaseTable<T> {
  List<T> _data;

  String _tableName;

  ClassMirror _tableClassMirror;
  AppReflectable _reflectable;

  DatabaseTable() {
    _reflectable = AppReflectable();
    _tableClassMirror = _reflectable.reflectType(T);
    _tableName = _getTableAnnotations().tableName;
  }

  Table _getTableAnnotations() {
    var modelTableNameMetadata = _tableClassMirror.metadata
        .firstWhere((element) => element == Table, orElse: () => null);

    if (modelTableNameMetadata == null) {
      throw NoTableNameFoundException(cause: "No table found");
    }

    print(modelTableNameMetadata);

    return modelTableNameMetadata as Table;
  }
}
```

Thanks anyway.

**Comment by eernstg** [comment]
Certainly, for instance https://github.com/dart-lang/test_reflectable/blob/master/test/meta_reflectors_test.dart is a multi-library test where 'main.dart' does `initializeReflectable();`, and various other libraries do things like declaring that a specific class should have reflection support, or it declares a subclass of `Reflectable` which is intended to be used as a reflector, and so on.

The static analysis performed as part of the reflectable code generation step has access to the transitive closure of libraries imported by the given target.

The target is supposed to be 'the program', which means that the code generation analysis has access to the whole program. If you do not follow this recommendation then the analysis may be unable to see some of the libraries of the program, and this means that it won't be able to generate data in the reflection database which describes classes in those libraries (so you may get reflection support for a class `C` by writing `@reflector class C {...}`, but if the code generation can't see the library where `C` is declared then the reflection support for that class is missing, and you may get a 'no such capability' error at runtime).

So the short version is "reflectable is inherently aimed at working on whole programs".

I'll close this issue because there is nothing to change &mdash; but don't hesitate to report it in another issue if you encounter buggy behaviors!
