### ISSUE TITLE
Reflecting on fields in a space efficient way

### ISSUE THREAD

**Issue by danschultz** [dart-lang/reflectable#38]
Is there a way to reflect on the fields of an instance without ballooning the size of the app? I'm using the `declarationsCapability` and `instanceInvokeCapability` and I'm seeing about 30kb increase of minified JS for a single reflected class.

Looking through the generated JS, it seems like it includes the type info for the instance's fields, those type's fields, and so on. I really don't care about the type info. I just want to iterate over the instance's fields and query their values.

**Comment by eernstg** [comment]
Hi Dan,

with recent versions of reflectable we have some implications: `declarationsCapability` is an instance of a subtype of the type of `typeCapability`, and this means that you cannot have `declarationsCapability` without `typeCapability`. The point is that you can never reach any declarations if you cannot reach any types, so `declarationsCapability` makes no sense without `typeCapability`. 

That was the first step. Second: When you have `typeCapability` you can also get a mirror of the class of a type annotation for any given declaration mirror (e.g., with a field among the declarations, you can get the class of the type annotation in the declaration of that variable, if any; similarly for method arguments and return types). We even follow that track recursively: If support for a class `C` causes support for a class `D` used as a type annotation in `C`, then you will also get support for class `E` if it is used in a type annotation in `D` (all of this: if your capabilities provide support for those members, which might not be the case if you are using `..Meta..` capabilities or using a non-trivial regexp). This is already enough of a reason to make your supported universe larger than you expect---and need, presumably. This also matches the situation as you described it.

If this is the right diagnostic then there is a solution which is just about to be released:

We have introduced the notion of `typeAnnotationQuatifyCapability` to give you more control. The idea is that the transitive closure of types reachable via type annotations is _not_ any more taken as soon as you have the `typeCapability` and `declarationsCapability`, we only take that step if you request it explicitly. 

You do that by including `typeAnnotationQuatifyCapability` or `typeAnnotationDeepQuatifyCapability` among your capabilities (both instances of a class but providing different arguments for a constructor argument called `transitive`); the former will cause type annotation classes to be included in one step, and the latter will run a fixed point iteration such that all reachable types (traversing declarations and their types) are included. With deep/transitive quantification we have the old behavior that you are probably using today. If you don't include any of them then you don't get any of the type annotation classes at all (except of course if you have included some of them in some other way).

You can get support for the new quantifiers by switching to commit 195e18b4a80d53ec6e09c0341871d386ee439bed of reflectable or something newer (not yet published, and it only implements the quantifiers for non-transformed code so you can test but you can't really see the space improvement; but it's just about ready for transformed code as well and then we'll publish it in a version '0.3.<something>').

I'm closing the issue now because I think the solution is upcoming. Please create a new issue if it turns out to be a different problem.

**Comment by danschultz** [comment]
Thanks, that sounds like what I'm looking for.

**Comment by danschultz** [comment]
Hey @eernstg, I tried out the latest release (0.3.2) and I'm having some issues with the new `typeAnnotationQuantifyCapability`. When reflecting on an instance, it returns `null` for `InstanceMirror.type`.

What I'm trying to do is define a class that I can mixin, and be able to inspect the values of the host. For example, something like:

```dart
class Person extends Object with Inspectable {
  final String name;
}

var person = new Person("Jim");
print(person.inspect()); // Person {name: "Jim"}
```

My `Reflectable` and mixin looks like this:

```dart
class ReflectSubtypes extends Reflectable {
  const ReflectSubtypes() : super(typeAnnotationQuantifyCapability, subtypeQuantifyCapability);
}

const _inspector = const ReflectSubtypes();

@ReflectSubtypes()
class Inspectable {
  Map<String, dynamic> inspectValues() {
    var mirror = _inspector.reflect(this);
    var valueMirrors = mirror.type.declarations.values.where((value) => value is VariableMirror);
    var valueMap = new Map.fromIterable(valueMirrors,
        key: (value) => value.simpleName,
        value: (value) => mirror.invokeGetter(value.simpleName));
    return valueMap;
  }

  String inspect() {
    return _inspectWithOptions();
  }

  String _inspectWithOptions({String indent: ""}) {
    var mirror = _inspector.reflect(this);
    var buffer = new StringBuffer();
    buffer.writeln("$indent${mirror.type.qualifiedName} {");

    inspectValues().forEach((key, value) {
      if (value is Inspectable) {
        value = value._inspectWithOptions(indent: "$indent  ").trim();
      }

      buffer.writeln("$indent  $key: $value");
    });

    buffer.writeln("$indent}");
    return buffer.toString();
  }
}
```

Any help on the correct capabilities to use would be appreciated.
