### ISSUE TITLE
instanceMembers fails after transform in some cases

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/reflectable#58]
I have a Reflector with `InstanceInvokeMetaCapability`, and in Dart (`vm,dartium,content-shell`) it works as expected. However after transform I get a weird error.

When I do this: `reflector.reflect(this).type.instanceMembers`

This part:

```dart
// src/reflectable_transformer_based.dart:183

  ReflectorData get _data {
    if (_dataCache == null) {
      _dataCache = data[_reflector];
    }
    return _dataCache;
  }
```

Fails in some way in Dart2JS, because the `data[_reflector]` throws the following error in JS:

```
  NullError: method not found: '$index' on null
  package:reflectable/src/reflectable_transformer_based.dart 185:20   _data
  package:reflectable/src/reflectable_transformer_based.dart 196:13   _InstanceMirrorImpl
  package:reflectable/src/reflectable_transformer_based.dart 195:3
  package:reflectable/src/reflectable_transformer_based.dart 2166:12  myProjectsFunctionName
  package:my_project/my_file.dart
```

I haven't encountered this error before, and I suspect it has something to do with encapsulation, maybe?
Both the metadata class and the reflectee class are public.

**Comment by eernstg** [comment]
Presumably, the `_data` field in the relevant class mirror is null. One reason for having this behavior comes to mind: If the analyzer does not resolve all libraries delivered to the reflectable transformer then the transformer gets null for the value of constants. The typical consequence is that the file for the entry point (if you transform 'web/index.dart' then the transformed entry point file is 'build/web/index.dart') contains a declaration like `final _data = {};`. This essentially means that the "reflection database" that enables the reflectable package to do all its work is empty; this again means that almost nothing works, so this is only a plausible explanation if you see this failure early---if other things are done using reflectable mirrors before that then it is not a likely cause.

To check for `final _data = {};` you can make sure that the Dart file is generated by using `pub build --mode=debug <whatever_you_usually_specify_as_target_eg_test>`, and then you can grep for '_data' in the transformed entry point file.

If this is the cause then it may be caused by a version skew: The analyzer up to version 0.26.1+14 delivered resolved libraries; for a while we used that, because newer versions delivered (some) libraries unresolved. Recently we updated to use analyzer version 0.27.1, because that one again delivers resolved libraries, but 0.27.1+1 again delivers (some) unresolved ones. With older versions of reflectable you'd use 0.26.1+14 (up to version 0.4.0), and the most recent one insists on 0.27.1, but v0.5.0 allows for newer versions (including 0.27.1+1).

If the problem is that you are using v0.5.0 rather than v0.5.1 then a simple `pub upgrade` should do it; if some other package prevents v0.5.1 or insists on analyzer 0.27.1+1-or-newer then it gets hairier, but you may wish to use a `dependency_overrides:` section in 'pubspec.yaml' and force a particular choice.

**Comment by emilniklas** [comment]
Thank you @eernstg! Very helpful. I'll get back to you in a bit.

**Comment by emilniklas** [comment]
Oh dearie me... I'm embarrassed. I had forgotten to add a new test file to `entry_points` and was confused why only that file got the strange JS error. My bad!
