### ISSUE TITLE
Bug in reflectable_mirror_based.dart

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/reflectable#63]
I was running test code and got this error:
```
type 'String' is not a subtype of type 'Symbol' of 'name'.
  package:reflectable/src/reflectable_mirror_based.dart 1704:24  MethodMirrorImpl._isArgumentListShapeAppropriate.<fn>
```

All reflectable API's use Strings instead of Symbols, so I guess somewhere along the way, it is not correctly converted into a Symbol.

This is the method itself:
```dart
  bool _isArgumentListShapeAppropriate(
      int numberOfPositionalArguments, Iterable<Symbol> namedArgumentNames) {
    if (numberOfPositionalArguments <
            numberOfPositionalParameters -
                numberOfOptionalPositionalParameters ||
        numberOfPositionalArguments > numberOfPositionalParameters) {
      return false;
    }
    if (namedArgumentNames == null) return true;
    return namedArgumentNames
        .every((Symbol name) => namesOfNamedParameters.contains(name));
  }
```
The last line throws the error.

**Comment by eernstg** [comment]
It is true that the reflectable API in general takes arguments of type `Symbol` where 'dart:mirrors' takes arguments of type `String`. However, the `namedArguments` given to various kinds of invocation (several methods named `invoke` and `newInstance`) have type `Map<Symbol, dynamic>`:

```dart
  ...
  Object invoke(String memberName,
                List positionalArguments,
                [Map<Symbol, dynamic> namedArguments]);
  ...
  Object newInstance(String constructorName,
                     List positionalArguments,
                     [Map<Symbol, dynamic> namedArguments]);
  ...
```

Presumably you have been using checked mode and passing an object of type `Map<dynamic, dynamic>`. That object would be able to masquerade as a `Map<Symbol, dynamic>` (and its `keys` would be an `Iterable<dynamic>` which could masquerade as an `Iterable<Symbol>`), and then you wouldn't get any checked-mode check failures before you take out one of the elements and find a `String` rather than a `Symbol`.

In general, I prefer using explicitly typed map/list literals, exactly because they won't pretend to have types that they don't have. If you do this then you'll get the checked mode failure already at `invoke` or `newInstance`. [You may know that there is an ongoing effort to introduce a 'strong mode' which is associated with inference of type arguments to some list/map literals, but it is unfortunately not in compliance with the Dart semantics to create an actual `List<int>` when you encounter `[2, 3]`, so the safe bet, so far, is to give the type arguments explicitly, as in `<int>[2, 3]`.)

The reason why we have this particular occurrence of `Symbol` in the API is that we did not want to modify the values passed as arguments in invocations (that's a base level concern, not a reflective one), and the set of named arguments given in an invocation can reasonably be considered to be a `Map<Symbol, dynamic>`. (The compiler can add extra checks for each key based on the type annotation on each named parameter, so we actually have something like a heterogeneous map here, which is an interesting concept ;-).

The reason why the Dart language per se justifies the claim that named arguments form a map whose keys are `Symbol`s is, among other things, that `Function.apply` accepts a map whose keys are `Symbol`s, and `noSuchMethod` receives an `Invocation` whose `namedArguments` are given as a map whose keys are `Symbol`s. Those things do not have any ties to 'dart:mirrors' (nor reflectable, of course), and they are specified in the language specification. Hence, *the names of named parameters are symbols*.

So I'll close the issue.

**Comment by stevenroose** [comment]
Hmm, it seems that you are right. However, I find the use of both Symbols and Strings quite confusing. Are there plans to clear that out, or will the API be fixed the way it is now?

**Comment by eernstg** [comment]
I agree that it is a somewhat surprising case, and we discussed it for a while before we landed it as it is today. I don't think it will be easy to change the language in this respect (in particular, `Invocation`, `noSuchMethod`, and `Function.apply`), simply because changes to the semantics of Dart will break so many programs.

Some people have argued that `Symbol` should be eliminated altogether (exactly because of this confusion about strings and symbols). You could also argue that it makes sense to have this division of labor, as in "Symbol: mainly compile-time values, canonicalized, language related; String: general purpose, dynamic".

But we certainly haven't changed our mind: it is more convenient to use strings for reflective operations than symbols. So there is no danger that we'll go back to use all symbols. ;-)
