### ISSUE TITLE
Allow wildcards in entry_points

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/reflectable#67]
It would be useful if wildcards are supported for the entry_points in pubspec.yaml just like it is supported for other packages. F.e. test allows wildcards for specifying `$include`.

**Comment by eernstg** [comment]
An entry point is not a file specification (that is, a string 's' such that `ls s` will succeed in a POSIX shell when invoked from the root of the current package). In particular, it uses '/' even on Windows.

Apart from that, shell wildcards come in many forms, e.g., some shells recognize `**` as a wildcard for a path rather than a file name (so it "searches all subdirectories"), and others will take '(.)' at the end to mean that only files would match (not directories, symlinks, ..), and there are lots of other potential rules, including "if an entry point matches a directory then it denotes all Dart files in that directory or any of its subdirectories", etc. So we would need to find a reasonable interpretation of what it means to match a wildcarded entry point to a given `Asset` that barback provides to the transformer.

It seems that test uses 'package:glob/glob.dart', and that might be a good choice --- it may not correspond to the behavior of any particular shell, but it could be "the Dart way" to do globbing, and it seems to be relatively unsurprising.

I think I'll put that into the transformer. But right now I'm traveling, so there will be about a week where comments on this idea can be added here.

**Comment by sigurdm** [comment]
Glob sounds like the obvious choice!

**Comment by jakemac53** [comment]
If all you want to support is globbing entry points, then that is effectively already supported today with `$include`. All you would need to do is add an option to reflectable that treats all inputs as primary inputs if the `entry_points` option is not supplied. Or you could require a special `all` or `*` value or something if you wanted to have it be more explicit.

**Comment by eernstg** [comment]
Wildcards for entry points are now supported (as of https://github.com/dart-lang/reflectable/commit/8936f98be71cd4325928b8b249b906f83aa54034). The rules for which wildcards can be used and how are available at https://pub.dartlang.org/packages/glob. Taking 'pubspec.yaml' in package test_reflectable as an example (scroll to the bottom of the linked page) this means that the explicit enumeration of about 65 entry points can be replaced by the more concise `entry_points: ["test/*_test.dart"]`.
