### ISSUE TITLE
Annotated model in Polymer app causing reflectable transformer to fail

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/reflectable#75]
This is a bit of a bizarre issue so let me give some context.

I have a codegen library that uses annotations on models to create serialization code. These models are then used within custom elements. I found that when running with reflectable 0.5.1 that it was having issues with a particular model of mine.

```dart
class Build {
  /// When the build request was received.
  @Serialize.field('created_at')
  DateTime createdAt;

  /// The login for the author of the commit.
  @Serialize.field('author')
  String author;
  ...
}
```

To use it within a Polymer view I end up creating a proxy object.

```dart
class BuildProxy extends JsProxy implements Build {
  @reflectable
  @override
  DateTime get createdAt => _model.createdAt;
  set createdAt(DateTime value) {
    _model.createdAt = value;
  }

  @reflectable
  @override
  String get author => _model.author;
  set author(String value) {
    _model.author = value;
  }

  ...
}
```

In the generated code there's this bit.

```dart
        new r.VariableMirrorImpl(
            r"createdAt",
            32773,
            52,
            const prefix0.JsProxyReflectable(),
            50,
            -1,
            -1,
            const <Object>[const prefix36.field('created_at')]),
```

The prefix36.field can't be found so running fails.

The weird thing is there are other values within that object that are reflectable and used in the view. The author field which is also being used within the view is not having this problem. Searching the generated code I don't see any other references to `field`.

If I comment out the `@Serialize.field` for the `createdAt` things go back to working.

The only thing I can think of is maybe its zeroing on `createdAt` because there's a `created` constructor in Polymer.

**Comment by jakemac53** [comment]
What does the `VariableMirrorImpl` for the  `author` field look like?

**Comment by donny-dont** [comment]
I actually don't see a `VariableMirrorImpl` only `MethodMirrorImpl`

**Comment by jakemac53** [comment]
What does that one look like?

**Comment by donny-dont** [comment]
```dart
        new r.MethodMirrorImpl(
            r"author",
            131075,
            15,
            47,
            47,
            47,
            const <int>[],
            const prefix0.JsProxyReflectable(),
            const <Object>[prefix40.reflectable, override]),
        new r.MethodMirrorImpl(
            r"author=",
            65540,
            15,
            null,
            null,
            null,
            const <int>[29],
            const prefix0.JsProxyReflectable(),
            const <Object>[]),
```

**Comment by jakemac53** [comment]
Oh ok, so those are for the `BuildProxy` class, not the `Build` class. I wonder why its picking up the `createdAt` field from the `Build` class and not the `author` field?

**Comment by jakemac53** [comment]
Ok, so I bet it is related to the `created` field in polymer, if you see https://github.com/dart-lang/polymer-dart/blob/master/lib/src/common/js_proxy.dart#L62 we always include those known methods so that you don't have to include an `@reflectable` annotation for them. Reflectable must just be doing a `startsWith` check or something to see if the names match up?

**Comment by jakemac53** [comment]
Still doesn't explain why the annotation actually messes things up though.

**Comment by donny-dont** [comment]
@jakemac maybe because of the `implements` on the proxy? Not sure if its looking at the fields in the implemented class. Not sure why it would explode in general though.

**Comment by eernstg** [comment]
This is a code generation bug. The transformer omits the class name in this case because it is mistakenly treated like `aLibraryPrefix.aClass(args)` which must be transformed to `prefix42.aClass(args)`. Working on it now.

**Comment by eernstg** [comment]
https://codereview.chromium.org/1689103002/

**Comment by eernstg** [comment]
Landed as  commit b02c674c8ecf7ab6b9f0814c76c927ea13fa2a0a.

**Comment by eernstg** [comment]
Closing now. I have no doubts that this commit resolves a bug. If I haven't guesstimated your situation completely and there are additional issues (I did make some guesses ;-) then please add more info here and I'll reopen.

**Comment by donny-dont** [comment]
@eernstg thank you! I'll give it a go ASAP.

I think there are a few issues here actually.

The first one with reflectable not being able to handle annotations with a named constructor. This looks to be solved by your commit.

The second one is why is reflectable generating code for this specific field and not the others? I'm not sure if its just because of the name as @jakemac53 postulated. Since reflectable is a transformer its hard to see what exactly was output. It doesn't seem like anything other than the createdAt got picked up by reflectable as something to export.

The third one is possibly related to the second one, can reflectable ignore certain annotations? In my case the annotations aren't accessed ever by the application. The annotations are there for running the code through the analyzer and then generating code to serialize it. If reflectable is generating code around these things then its generating code that will never be hit because I'm never going to ask for it.

**Comment by jakemac53** [comment]
> The third one is possibly related to the second one, can reflectable ignore certain annotations? In my case the annotations aren't accessed ever by the application. The annotations are there for running the code through the analyzer and then generating code to serialize it. If reflectable is generating code around these things then its generating code that will never be hit because I'm never going to ask for it.

Polymer is telling reflectable that it wants to reflect on annotations. I think there are already some options available to tell it which annotations it wants to reflect on, so I could explore restricting that.

**Comment by eernstg** [comment]
About 'Since reflectable is a transformer its hard to see what exactly was output': If you use `pub build --mode=debug your-source-directory` you should have the source available on disk. For instance, if 'web/myEntryPoint.dart' is declared to be an entry point then the transformed version of the corresponding program will consist of 'build/web/myEntryPoint.dart' (the generated library), 'build/web/myEntryPoint_reflectable_original_main.dart' (identical to 'web/myEntryPoint.dart'), and remaining libraries (transferred without changes). But you already quoted code like `new r.MethodMirrorImpl(..)` so you know all this already, right?

But I think the core problem here may be quite different. Any given reflector (i.e., instance of a direct subclass of `Reflectable`) provides a mirror system which may or may not provide support for a given class such as `Build`. You get support for a class by a reflector by adding it as metadata to the class (as in `@reflector class Build ..`), or by using a quantifier (e.g., by having `@reflector` on a superclass and having `subtypeQuantifyCapability` on `reflector`).

The reflector will then support members based on the capabilities. If you choose to quantify "manually" by including all members carrying a specific type of metadata then you need to have capabilities like `instanceInvokeMetaCapability(M)` in order to be able to invoke instance methods carrying `@M(..)` as metadata (and in order to have them included in `declarations`, etc.). In particular, if `Serialize.field('..')` has type T then you would have a `..MetaCapability(S)` for some S which is a supertype of T (possibly T itself).

If you intend to use the polymer reflector (`JsProxyReflectable`) then you may be able to include support for whatever methods you wish: it includes `const InstanceInvokeMetaCapability(PolymerReflectable)` so if `Serialize.field(..)` can implement `PolymerReflectable` you should be on track.

If you are using your own reflector then you can choose freely what the requirement is, for instance by adding `const InstanceInvokeMetaCapability(T)` for any type T that is a supertype of the type of `Serialize.field(..)`.

In both cases you need to check that `Build` and other classes that you wish to serialize are actually covered by the chosen reflector.

**Comment by eernstg** [comment]
Ah, I suddenly realize what that `startsWith` business was about: `JsProxyReflectable` includes capabilities on the form `const ...InvokeCapability(_knownMethodAndPropertyNames)`; the argument is use in a `RegExp` and the test is whether there is a match. It may be useful to constrain `_knownMethodAndPropertyNames` further with `^(..)$`, such that it only matches complete method names.

With that, the picture is much clearer: It is indeed `JsProxyReflectable` which is being used as the mirror system for the main topic of this issue: `Build` is a subtype of `JsProxy` which is covered by `JsProxyReflectable` which has a `subtypeQuantifyCapability`, and `createdAt` matches `..|created|..` by accident.

The next step is to make sure that `Serialize.field(..)` has a type that implements `PolymerReflectable`.

**Comment by donny-dont** [comment]
> About 'Since reflectable is a transformer its hard to see what exactly was output': If you use pub build --mode=debug your-source-directory you should have the source available on disk. For instance, if 'web/myEntryPoint.dart' is declared to be an entry point then the transformed version of the corresponding program will consist of 'build/web/myEntryPoint.dart' (the generated library), 'build/web/myEntryPoint_reflectable_original_main.dart' (identical to 'web/myEntryPoint.dart'), and remaining libraries (transferred without changes). But you already quoted code like new r.MethodMirrorImpl(..) so you know all this already, right?

I actually did not know that was the case. The error info was from when I ran the code. Thanks for the tip!

Thanks @jakemac53 and @eernstg for taking a deep look at this. It seems like there's a good handle on what went wrong here.

**Comment by eernstg** [comment]
Very good, and thanks for your input! If `implements PolymerReflectable` doesn't cut it then we'll take another round.
