### ISSUE TITLE
Metadata is not available for synthetic getters/setters

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/reflectable#78]
So I was porting over some code based on raw mirrors that processes annotations, including those on superclasses and mixins and ran into the issue that the synthetic getter/setter method mirrors that wrap variables accessed through `InstanceMirror#instanceMembers` do not expose metadata. I assume this is a known issue, but the discrepancy is highly confusing and I could not find it documented anywhere. 

As far as I understand my only option here is to use `ClassMirror#declarations` which means walking the class hierarchy manually. In all fairness this is also what I did with raw mirrors but it would be really nice and much less confusing if reflectable could provide the metadata for all instance members. At least is should be documented. 

The following program illustrates my issues:

``` dart
import 'package:reflectable/reflectable.dart';

class ReflectableClass extends Reflectable {
  const ReflectableClass()
      : super(const InvokingMetaCapability(MyAnnotation), metadataCapability,
            declarationsCapability);
}

class MyAnnotation {
  const MyAnnotation();
}

@ReflectableClass()
class Foo {
  @MyAnnotation()
  var kittens;

  @MyAnnotation()
  get puppies {}
}

@ReflectableClass()
class Bar extends Foo {
  @MyAnnotation()
  var ponies;

  @MyAnnotation()
  get unicorns {}
}

void main() {
  final barMirror = const ReflectableClass().reflectType(Bar);
  print('bar instance members:');
  barMirror.instanceMembers.forEach(_print);

  print('\nbar declarations:');
  barMirror.declarations.forEach(_print);
}

_print(name, mirror) =>
    print('\t${mirror.runtimeType} on $name metadata: ${mirror.metadata}');
```

Output:
```
bar instance members:
	ImplicitGetterMirrorImpl on kittens metadata: []
	ImplicitSetterMirrorImpl on kittens= metadata: []
	MethodMirrorImpl on puppies metadata: [Instance of 'MyAnnotation']
	ImplicitGetterMirrorImpl on ponies metadata: []
	ImplicitSetterMirrorImpl on ponies= metadata: []
	MethodMirrorImpl on unicorns metadata: [Instance of 'MyAnnotation']

bar declarations:
	VariableMirrorImpl on ponies metadata: [Instance of 'MyAnnotation']
	MethodMirrorImpl on unicorns metadata: [Instance of 'MyAnnotation']

```

**Comment by eernstg** [comment]
Right, we consider the synthetic getters/setters to have no metadata. However, it would be trivial to change `ImplicitAccessorMirrorImpl` to have `List<Object> get metadata => _variableMirror.metadata` rather than `List<Object> get metadata => <Object>[]`, and not much worse for pre-transformed code. I'll think about it, but most likely there is no problem with that change, and then I'll do it later this week.

**Comment by lassedamgaard** [comment]
That would be awesome Erik. Just out of curiosity, could you describe why they're considered to not have metadata? It sounds like you made a conscious choice to omit it.

**Comment by eernstg** [comment]
They don't have metadata because metadata arises when a declaration is syntactically associated with a phrase on the form `@ <qualified> (. <identifier>)? (<arguments>)?)*`; synthetic getters/setters have no syntax, so they are not syntactically associated with anything, including anything on that form. ;-)

But it still makes sense to say that there are no benefits in insisting on such a strict interpretation (your examples illustrate that quite well), so we might as well deliver the metadata of the associated variable declaration. It is still possible for programmers to check `isSynthetic` and ignore the metadata, if they prefer the strict interpretation.

**Comment by lassedamgaard** [comment]
That makes sense. For the record I just implemented this using `ClassMirror#declarations` which considering how trivial that is, is probably preferable if - as in my case - the distinction between properties and variables matters.

**Comment by eernstg** [comment]
Given that the model is nicely consistent today ("no syntax means no metadata"), and given that this model seems to work reasonably well in practicel, I'll change this to `wontfix` and close it.
