### ISSUE TITLE
Transform Reflectable threw error: The null object does not have a getter 'source'.

### ISSUE THREAD

**Issue by pjjjv** [dart-lang/reflectable#88]
I see a cryptic build error, both when using dartium as when using dart2js. This is a messy Polymer.dart (Polymer 1.0) project.

```
Build error:
Transform Reflectable on akepot|web/akepot.bootstrap.initialize.dart threw error: The null object does not have a getter 'source'.

NoSuchMethodError: method not found: 'source'
Receiver: null
Arguments: []
dart:core-patch/object_patch.dart 42                             Object._noSuchMethod
```

https://gist.github.com/anonymous/b9bf83682c0e0919564ef699ff026110

**Comment by eernstg** [comment]
Apparently, an `Element` from the Dart analyzer turned out to have a null `.library` during transformation of your project. I wouldn't expect that to happen, though, so there's definitely a need for more information. Could you give more information about the setting? (pubspec.lock to see the versions, preferably source of the project if you can make it available..).

**Comment by pjjjv** [comment]
Source of the project is https://github.com/pjjjv/Akepot/commit/f2464b89dbe0582835d5a473ead7dfcf297a0869. I'm migrating my project from polymer 0.15 to 1.0.0.

**Comment by pjjjv** [comment]
If you look at the following code that gives the error: https://github.com/pjjjv/Akepot/commit/22b8d22fe664aec754a59154988f673807160e42

Remove the below code and it'll build:


```
  @reflectable
  void ajaxError(CustomEventWrapper event, {request: IronRequest, error: dynamic}) {
    if (DEBUG) print(event.detail);
  }
```

**Comment by eernstg** [comment]
Looking into your project, I found something which is clearly a bug (the analyzer representation of the `dynamic` type turns out to have a null library, which isn't expected at the relevant point in the transformer).

This has been fixed in https://github.com/dart-lang/reflectable/commit/65963c7a50ca9180bf48172c0cfbb8e32c961044, so you should be able to proceed with your project by fetching the most recent commit from github.com/dart-lang/reflectable and using a suitable `path:` in pubspec.yaml. The fix will of course also be part of the next published version.

The issue was closed by the commit; please request a re-opening if you think there is more to it.

**Comment by eernstg** [comment]
By the way, it looks like you intended to declare some named arguments `request` and `error` with types `IronRequest` and `dynamic`, respectively, but you've actually declared them to have type `dynamic` (both types omitted), with default values `IronRequest` and `dynamic` (both of which are instances of type `Type`, and none of which are likely to be useful). So this could fail because nobody has used such a default value in any test cases before.

The likely fix would look like this: 
```dart
  @reflectable
  void ajaxError(CustomEventWrapper event, {IronRequest request, error}) {
    ...
  }
```
And yes, we do have requests to change `:` to `=` to avoid this type of confusion.  ;-)
