### ISSUE TITLE
Invalid argument(s) exception using native extensions

### ISSUE THREAD

**Issue by StepFischer** [dart-lang/reflectable#92]
Hello,

we've currently have an issue using a encryption package, which utilises the reflectable package.

The design of our web server uses native extensions to call functions from a C++ library we wrote ourselves.
Running the web server leads to the error:

```
Cought exception:
Error: Invalid argument(s)
Stacktrace:
#0      _LocalLibraryDependencyMirror._tryUpgradePrefix (dart:mirrors-patch/mirrors_impl.dart:1340)
#1      _LocalLibraryDependencyMirror.targetLibrary (dart:mirrors-patch/mirrors_impl.dart:1323)
#2      ReflectableImpl._directlySupportedClasses (package:reflectable/src/reflectable_mirror_based.dart:2303:24)
#3      ReflectableImpl._supportedClasses.<anonymous closure> (package:reflectable/src/reflectable_mirror_based.dart:2387:36)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:262)
#5      ReflectableImpl._supportedClasses (package:reflectable/src/reflectable_mirror_based.dart:2386:35)
#6      ReflectableImpl.annotatedClasses (package:reflectable/src/reflectable_mirror_based.dart:2284:12)
#7      FactoryRegistry.initialize (package:pointycastle/src/registry/registry.dart:92:41)
#8      FactoryRegistry._checkInit (package:pointycastle/src/registry/registry.dart:87:7)
#9      FactoryRegistry.createConstructor (package:pointycastle/src/registry/registry.dart:64:5)
#10     FactoryRegistry.getConstructor (package:pointycastle/src/registry/registry.dart:56:21)
#11     FactoryRegistry.create (package:pointycastle/src/registry/registry.dart:48:42)
#12     SecureRandom.SecureRandom (package:pointycastle/src/api/secure_random.dart:20:16)
#13     Encryption.Encryption.Init (package:ourpackage)
#14     OurProgram (package:ourpackage)
#15     main (file:///...)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Process finished with exit code 2
```

> Note: Naming of internal packages are obfuscated in the upper stacktrace

This error occurs at [reflectable_mirror_based.dart line 2303](https://github.com/dart-lang/reflectable/blob/master/reflectable/lib/src/reflectable_mirror_based.dart#L2303) while the program scans the dependencies of our native extension dart class.

The reason, why it throws an exception is, that the value `dependency.targetLibrary.qualifiedName` is `null` (or some other undefined value). We already tried to made some changes to our native extension class in dart, to investigate any solution. But we had no luck.

Could you provide us some advise, how to use native extensions along side reflectables?
If we found a bug in the package, we are pleased to support you with more information to solve this issue.

Best regards,

Stephan Fischer
quapona technologies GmbH

**Comment by eernstg** [comment]
The `targetLibrary` is in fact allowed to return `null`, and reflectable_mirror_based.dart did not take that into account. [This cl](https://codereview.chromium.org/2711153002/) addresses that issue.

But this does not actually seem to be the reason for the failure you're seeing. It looks like the evaluation of `dependency.targetLibrary.qualifiedName` fails because `dependency.targetLibrary` fails, because it calls the native function `_tryUpgradePrefix` with an argument which it considers to be invalid. That argument is provided when the `_LocalLibraryDependencyMirror` is created and it is never changed except for one case (which is by the way the place where `_tryUpgradePrefix` is called):
```dart
    var mirrorOrNull = _tryUpgradePrefix(_targetMirrorOrPrefix);
    if (mirrorOrNull != null) {
      _targetMirrorOrPrefix = mirrorOrNull;
    }
```
Since `_LocalLibraryDependencyMirror` is a private class in a core library, there couldn't be any user code which creates instances of this class, and there are actually no invocations of the constructor in the library itself, so all instances must be created by core native code, and that constructor argument must be provided there. In particular, there is no way reflectable (with or without transformation) could create this problem.

I suspect that you would see the same failure with the following:
```dart
import 'dart:mirrors';
// Here: Add imports such that your native stuff is included.

main() {
  for (LibraryMirror library in currentMirrorSystem().libraries.values) {
    for (LibraryDependencyMirror dependency in library.libraryDependencies) {
      print(dependency.targetLibrary);
    }
  }
}
```
In that case it is a 'dart:mirrors' issue.

**Comment by eernstg** [comment]
Landed that CL in [this commit](https://github.com/dart-lang/reflectable/commit/16b3d5665cd4130b670a1eb6b92e1597001ecc20).

**Comment by StepFischer** [comment]
Hello Mr. Ernst,

tank you for your quick reply.

I've executed the test code above and got the same error:
```
LibraryMirror on 'dart.async'
LibraryMirror on 'dart.isolate'
Error: Invalid argument(s)
Stacktrace:
#0      _LocalLibraryDependencyMirror._tryUpgradePrefix (dart:mirrors-patch/mirrors_impl.dart:1340)
#1      _LocalLibraryDependencyMirror.targetLibrary (dart:mirrors-patch/mirrors_impl.dart:1323)
#2      ourprogram (package:...)
#3      main (file:///...)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

So I will go to the dartlang/sdk github and add the issue there?
Second, when can we expect your patch to be available from the pub system?

Best regards,

Stephan Fischer
quapona technologies

**Comment by StepFischer** [comment]
We've integrated your patch in the commit [16b3d5665cd4130b670a1eb6b92e1597001ecc20](https://github.com/dart-lang/reflectable/commit/16b3d5665cd4130b670a1eb6b92e1597001ecc20), but the error still remains the same.

**Comment by StepFischer** [comment]
If have added an issue to the dart-lang/sdk [here](https://github.com/dart-lang/sdk/issues/28881)

**Comment by eernstg** [comment]
I'll create a new release and publish it on pub.dartlang.org, hopefully later today.
Thanks for submitting the dart-lang/sdk issue, I believe that's where the next steps can be taken.

I still suspect, though, that the underlying problem is that the vm is surprised by your native extensions. Not sure who is to blame for that ;-), but I'm not the right person to claim anything about how to integrate native extensions with the vm. So that discussion would probably also be in the right context in the sdk issue.

**Comment by eernstg** [comment]
The update has been published on pub.dartlang.org as [v1.0.2](https://pub.dartlang.org/packages/reflectable).

**Comment by StepFischer** [comment]
Thank you very much.
