### ISSUE TITLE
Raise analyzer version contraint

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/reflectable#96]
Is there any reason for keeping  `analyzer` version  `< 0.30` ?

**Comment by eernstg** [comment]
Not specifically; I'll look into the versions of all dependencies.

**Comment by dam0vm3nt** [comment]
tnx! this is  blocking from using latest `build_runner` in a project using `reflectable` 'cause it needs a more recent version of the `analyzer` .

**Comment by eernstg** [comment]
It turns out that enabling analyzer version 0.30.0 or later also implies a _lower_ bound of 0.30.0: when reflectable is updated to work with the newer versions of analyzer, it doesn't work with older versions any more.

This means that it breaks code that can't yet work with analyzer ^0.30.0, for whatever reason, so we will probably have to mark this transition as "somewhat breaking", maybe by switching to version 1.1.0. I'm just about to go on vacation (one week), and there's currently an infrastructure problem that prevents the build bots from running the tests, so I can't currently get a robust confirmation that it works on all platforms. Because of these issues I won't publish the resulting package before I get back.

However, the update has been landed on github, so if you're able to use a local copy of reflectable you should be able to do it approximately as follows:
```
> cd /some/path
> git clone https://github.com/dart-lang/reflectable.git
> cd reflectable
> git co b0c003f42871c4cc48b7f02f1c932021fea1f26b
```
and then using a local `path` dependency in packages that depend on reflectable:
```
dependencies:
  reflectable:
    path: /some/path/reflectable/reflectable
```
(A `git:` dependency in pubspec.yaml won't do, because it is unable to specify that the package is in a subdirectory of the repository).

**Comment by dam0vm3nt** [comment]
k, tnx! I'll use the path dep from the cloned repo until it's published.

**Comment by daniel-v** [comment]
Can we get an update on this?

**Comment by eernstg** [comment]
Sorry about the delay, it wasn't immediately obvious which approach would work well enough: I'm not happy about introducing very strong version constraints on clients.

However, I found a work-around (expressed in https://codereview.chromium.org/3000403002/) which makes the code work with both older and newer versions of the analyzer. So that should be non-breaking for all.

I expect to publish a new version of reflectable based on that approach within a few days.

**Comment by eernstg** [comment]
After some further discussion we decided to publish the previous version anyway (the one that won't work with analyzer version <0.30.0). The reasoning is that even though this is a breaking change (clients who want to use reflectable 1.0.4 must update their own analyzer dependencies to include versions 0.30.0 and up), but they will then just keep on using reflectable 1.0.3, which would behave the same for them.

[Here](https://pub.dartlang.org/packages/reflectable)'s the newly published package.
